version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Use custom Nginx configuration
      - ./ImageSets:/var/www/imagesets  # Serve images from this folder
    depends_on:
      - django_server
  django_server:
    build:
      context: .
      dockerfile: Dockerfile-django
    container_name: django_server
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
      - "5678:5678"  # Expose debugpy port for VS Code
    environment:
      - ENABLE_DEBUGGER=1

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    command: >
      python -Xfrozen_modules=off
      -m celery
      -A config
      worker --loglevel=info
    container_name: celery_worker
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0  # Set broker URL
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Set result backend
      # - ENABLE_DEBUGGER=1  # Enable debugger in container
    # ports:
      # - "5678:5678"  # Map debug port for VS Code
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
