# Dockerfile-django

# Use the official Python image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Install Poetry
RUN pip install --no-cache-dir poetry

# Copy only the dependency files
COPY pyproject.toml poetry.lock ./

# Install dependencies without creating a virtual environment
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

# Expose the Django server port
EXPOSE 8000

# Default command to run the Django server
CMD ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]
